#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 5.00.07.dev (2021-01-22)
# user:         sam
# date:         Tue Jan 26 05:42:01 America/Denver 2021
# host:         RoaringFork
# directory:    C:\Users\sam\cdss-dev\StateDMI\git-repos\cdss-app-statedmi-test\test\regression\commands\ReadCropPatternTSFromHydroBase
# command line: StateDMI
#  -home test\operational\CDSS
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Users\sam\cdss-dev\StateDMI\git-repos\cdss-app-statedmi-test\test\regression\commands\ReadCropPatternTSFromHydroBase\Test_ReadCropPatternTSFromHydroBase_cm2015ex_ge20200720.StateDMI"
# Commands: 
# # Test reading crop pattern TS (*.cds) data from HydroBase
# # - cm2015 locations for various location types
# # - HydroBase has irrigated lands for ? in the requested period
# #
# # Works with the following:
# #@require datastore HydroBase >= 20200720
# #
# StartLog(LogFile="Results/Test_ReadCropPatternTSFromHydroBase_cm2015ex_ge20200720.StateDMI.log")
# RemoveFile(InputFile="Results\Test_ReadCropPatternTSFromHydroBase_cm2015ex_ge20200720_out.cds",IfNotFound=Ignore)
# SetOutputPeriod(OutputStart="1950",OutputEnd="2007")
# #
# # Define locations and collections
# #
# # Explicit structure
# SetCULocation(ID="3600507",IfNotFound=Add)
# # Aggregate with relatively small number of parts
# SetCULocation(ID="38_ADC040",IfNotFound=Add)
# SetDiversionAggregate(ID="38_ADC040",PartIDs="3800557,3800635,3800724,3800732,3800823,3800845,3800997")
# # System with relatively small number of parts
# # - Roan Creek No 2
# SetCULocation(ID="7000583_D",IfNotFound=Add)
# SetDiversionSystem(ID="7000583_D",PartIDs="7000583,7000507")
# # MultiStruct
# # - SMITH DITCH
# SetCULocation(ID="3600801",IfNotFound=Add)
# SetDiversionMultiStruct(ID="3600801",PartIDs="3600801,3600832")
# #
# # Create the crop pattern time series
# CreateCropPatternTSForCULocations(ID="*",Units="ACRE")
# ReadCropPatternTSFromHydroBase(ID="*")
# # Uncomment the following command to regenerate the expected results.
# WriteCropPatternTSToStateCU(OutputFile="ExpectedResults/Test_ReadCropPatternTSFromHydroBase_cm2015ex_ge20200720_out.cds")
# WriteCropPatternTSToStateCU(OutputFile="Results/Test_ReadCropPatternTSFromHydroBase_cm2015ex_ge20200720_out.cds")
# CompareFiles(InputFile1="ExpectedResults/Test_ReadCropPatternTSFromHydroBase_cm2015ex_ge20200720_out.cds",InputFile2="Results/Test_ReadCropPatternTSFromHydroBase_cm2015ex_ge20200720_out.cds",IfDifferent=Warn)
# #
# # The following show the raw data and can be used for troubleshooting
# # ReadTableFromDataStore(DataStore="HydroBase",Sql="SELECT * from vw_CDSS_ParcelUseTSStructureToParcel where wd = 20 and (cal_year >= 1950 and cal_year <= 2007) and id in (505, 631, 812) order by id, cal_year, land_use",TableID="Test_ParcelUseTS")
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase_CO_20200720 on RoaringFork
# HydroBase.db_version:  design version: 20200720  last data change: 20200125
# HydroBase table structure for software is at least 2020072020200720
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (6x,i4,5x,6x,i4,a5,a5)
#>
#>  year1            :  Beginning year of data (calendar year).
#>  year2            :  Ending year of data (calendar year).
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>                      >= 0.0 in years with irrigated lands data or filled years.
#>                      -999 in years without irrigated lands data and have not been filled.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0) - INFO ONLY.
#>                      Equal to total/crop acres.
#>                      Fractions should add to 1.0.
#>                      >= 0.0 in years with irrigated lands data or filled years.
#>                      -999 in years without irrigated lands data and have not been filled.
#>  Acres       acres:  Acreage for crop.
#>                      Should sum to the total acres.
#>
#>Yr  CULocation                   TotalArea   NCrop
#>-exb----------exxxxxxxxxxxxxxxxxxb--------eb--------e
#>     CropName                    Fraction    Acres
#>xxxb----------------------------eb--------eb--------e
#>EndHeader
      1950           2007 ACRE CYR  
1950 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1950 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1950 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1950 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1951 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1951 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1951 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1951 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1952 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1952 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1952 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1952 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1953 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1953 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1953 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1953 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1954 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1954 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1954 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1954 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1955 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1955 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1955 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1955 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1956 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1956 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1956 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1956 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1957 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1957 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1957 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1957 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1958 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1958 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1958 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1958 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1959 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1959 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1959 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1959 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1960 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1960 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1960 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1960 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1961 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1961 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1961 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1961 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1962 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1962 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1962 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1962 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1963 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1963 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1963 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1963 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1964 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1964 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1964 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1964 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1965 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1965 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1965 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1965 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1966 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1966 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1966 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1966 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1967 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1967 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1967 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1967 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1968 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1968 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1968 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1968 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1969 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1969 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1969 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1969 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1970 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1970 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1970 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1970 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1971 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1971 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1971 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1971 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1972 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1972 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1972 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1972 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1973 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1973 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1973 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1973 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1974 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1974 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1974 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1974 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1975 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1975 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1975 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1975 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1976 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1976 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1976 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1976 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1977 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1977 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1977 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1977 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1978 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1978 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1978 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1978 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1979 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1979 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1979 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1979 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1980 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1980 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1980 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1980 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1981 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1981 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1981 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1981 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1982 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1982 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1982 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1982 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1983 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1983 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1983 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1983 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1984 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1984 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1984 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1984 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1985 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1985 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1985 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1985 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1986 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1986 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1986 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1986 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1987 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1987 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1987 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1987 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1988 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1988 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1988 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1988 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1989 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1989 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1989 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1989 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1990 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1990 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1990 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1990 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1991 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1991 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1991 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1991 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1992 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1992 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1992 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1992 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1993 3600507                           24.880         1
     GRASS_PASTURE                      1.000    24.880
1993 38_ADC040                        357.050         3
     ALFALFA                            0.329   117.352
     GRASS_PASTURE                      0.671   239.698
     SMALL_GRAINS                       0.000     0.000
1993 7000583_D                        104.759         3
     ALFALFA                            0.139    14.550
     GRASS_PASTURE                      0.663    69.456
     SMALL_GRAINS                       0.198    20.753
1993 3600801                          635.454         1
     GRASS_PASTURE                      1.000   635.454
1994 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1994 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1994 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1994 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1995 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1995 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1995 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1995 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1996 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1996 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1996 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1996 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1997 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1997 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1997 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1997 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1998 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1998 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1998 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1998 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1999 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
1999 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1999 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
1999 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2000 3600507                           37.204         1
     GRASS_PASTURE                      1.000    37.204
2000 38_ADC040                        304.199         3
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      0.879   267.426
     SMALL_GRAINS                       0.121    36.773
2000 7000583_D                        270.325         3
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      1.000   270.325
     SMALL_GRAINS                       0.000     0.000
2000 3600801                          269.060         1
     GRASS_PASTURE                      1.000   269.060
2001 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2001 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2001 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2001 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2002 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2002 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2002 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2002 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2003 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2003 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2003 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2003 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2004 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2004 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2004 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2004 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2005 3600507                           36.988         1
     GRASS_PASTURE                      1.000    36.988
2005 38_ADC040                        309.659         3
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      1.000   309.659
     SMALL_GRAINS                       0.000     0.000
2005 7000583_D                        380.833         3
     ALFALFA                            0.000     0.000
     GRASS_PASTURE                      1.000   380.833
     SMALL_GRAINS                       0.000     0.000
2005 3600801                          269.059         1
     GRASS_PASTURE                      1.000   269.059
2006 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2006 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2006 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2006 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2007 3600507                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
2007 38_ADC040                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2007 7000583_D                       -999.000         3
     ALFALFA                         -999.000  -999.000
     GRASS_PASTURE                   -999.000  -999.000
     SMALL_GRAINS                    -999.000  -999.000
2007 3600801                         -999.000         1
     GRASS_PASTURE                   -999.000  -999.000
