#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 5.00.07.dev (2021-01-22)
# user:         sam
# date:         Sun Jan 24 14:29:01 America/Denver 2021
# host:         RoaringFork
# directory:    C:\Users\sam\cdss-dev\StateDMI\git-repos\cdss-app-statedmi-test\test\regression\commands\ReadCropPatternTSFromHydroBase
# command line: StateDMI
#  -home test\operational\CDSS
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Users\sam\cdss-dev\StateDMI\git-repos\cdss-app-statedmi-test\test\regression\commands\ReadCropPatternTSFromHydroBase\Test_ArkExSimple.StateDMI"
# Commands: 
# StartLog(LogFile="Results/Test_ArkExSimple.StateDMI.log")
# # CDS command file for Arkansas River Example - testing legacy StateDMI functionality
# #@require datastore HydroBase >= 20200720
# #@require application StateDMI >= 5.00.00
# #
# # Remove output file from previous run.
# RemoveFile(InputFile="Results/Test_ArkExSimple_out.cds",IfNotFound=Ignore)
# #
# # Step 1 - Set output period and read CU locations
# SetOutputPeriod(OutputStart="2000",OutputEnd="2016")
# ReadCULocationsFromList(ListFile="Data/ArkEx_StructList.csv",IDCol=1)
# #
# # Step 2 - Read SW aggregates, divsys, and GW aggregates
# SetDiversionSystemFromList(ListFile="Data/ArkEx_SWDivSys.csv",IDCol="1",NameCol="2",PartIDsCol="3",PartsListedHow=InRow)
# SetDiversionAggregateFromList(ListFile="Data/ArkEx_SWAgg.csv",IDCol="1",NameCol="2",PartIDsCol="3",PartsListedHow=InColumn)
# #
# SetWellSystemFromList(ListFile="Data/ArkEx_GWAgg_Only.csv",PartType=Well,IDCol="1",PartIDsCol="2",PartIDTypeColumn="3",PartsListedHow=InColumn,IfNotFound=Warn)
# #
# # Step 3 - Initialize *.cds and read acreage/crops from HydroBase
# CreateCropPatternTSForCULocations(ID="*",Units="ACRE")
# ReadCropPatternTSFromHydroBase(ID="*",InputStart="2003",InputEnd="2016")
# #
# # Step 4 - Read well rights and determine gw-only structure acreage in 1950
# # TODO smalers 2021-01-23 need to enable
# # ReadWellRightsFromStateMod(InputFile="ArkEx_Simple_HB20180529.wer")
# # FillCropPatternTSUsingWellRights(ID="*",IncludeSurfaceWaterSupply=False,CropType="*",FillStart=1950,FillEnd=1955,ParcelYear=1956)
# #
# # Step 5 -
# #      Fill SW structure acreage backward from 2003 back to 2000
# #      Linearly interpolate acreage for all structures between 2003, 2010, and 2015 snapshots
# #      Use 2015 and 2016 snapshots for their years
# #
# FillCropPatternTSRepeat(ID="*",CropType="*",FillStart=2000,FillEnd=2003,FillDirection=Backward)
# FillCropPatternTSInterpolate(ID="*",CropType="*",FillStart=2003,FillEnd=2010)
# FillCropPatternTSInterpolate(ID="*",CropType="*",FillStart=2010,FillEnd=2015)
# #
# # Step 6 - Set primary WDID of Demand Structure = 0, and structures with no acreage in HydroBase = 0
# SetCropPatternTS(ID="6700610",CropPattern="ALFALFA,0,CORN_GRAIN,0,SUGAR_BEETS,0,GRASS_PASTURE,0,VEGETABLES,0,SPRING_GRAIN,0",IrrigationMethod=Flood,SupplyType=Ground,ProcessWhen=Now)
# #
# # Step 7 - Translate crop names to Locally Calibrated based on structure location and elevation
# # ALFALFA
# TranslateCropPatternTS(ID="*",OldCropType="ALFALFA",NewCropType="ALFALFA.TR21")
# #
# # BARLEY - Spring Grain TR21 coefficients used in RGDSS and SPDSS to represent barley, oats, and wheat under the name "Small Grains"
# TranslateCropPatternTS(ID="*",OldCropType="BARLEY",NewCropType="SMALL_GRAINS.TR21")
# #
# # BLUEGRASS
# TranslateCropPatternTS(ID="*",OldCropType="BLUEGRASS",NewCropType="BLUEGRASS.POCHOP")
# #
# # CORN_GRAIN
# TranslateCropPatternTS(ID="*",OldCropType="CORN",NewCropType="CORN_GRAIN.TR21")
# #
# # DRY_BEANS
# TranslateCropPatternTS(ID="*",OldCropType="DRY_BEANS",NewCropType="DRY_BEANS.TR21")
# #
# # GRASS_PASTURE
# TranslateCropPatternTS(ID="*",OldCropType="GRASS_PASTURE",NewCropType="GRASS_PASTURE.TR21")
# #
# # ORCHARD_WO_COVER
# TranslateCropPatternTS(ID="*",OldCropType="ORCHARD_WO_COVER",NewCropType="ORCHARD_WO_COVER.TR21")
# #
# # POTATOES
# TranslateCropPatternTS(ID="*",OldCropType="POTATOES",NewCropType="POTATOES.TR21")
# #
# # SMALL_GRAINS
# TranslateCropPatternTS(ID="*",OldCropType="SMALL_GRAINS",NewCropType="SPRING_GRAIN.TR21")
# #
# # SNAP_BEANS
# TranslateCropPatternTS(ID="*",OldCropType="SNAP_BEANS",NewCropType="SNAP_BEANS.TR21")
# #
# # SOD_FARM
# TranslateCropPatternTS(ID="*",OldCropType="SOD_FARM",NewCropType="BLUEGRASS.POCHOP")
# #
# # SORGHUM_GRAIN
# TranslateCropPatternTS(ID="*",OldCropType="SORGHUM_GRAIN",NewCropType="SORGHUM_GRAIN.TR21")
# #
# # SUNFLOWER - CU monthly and annual amount for sunflower is fairly close to sorghum
# TranslateCropPatternTS(ID="*",OldCropType="SUNFLOWER",NewCropType="SORGHUM_GRAIN.TR21")
# #
# # SUGAR_BEETS
# TranslateCropPatternTS(ID="*",OldCropType="SUGAR_BEETS",NewCropType="SUGAR_BEETS.TR21")
# #
# # VEGETABLES
# TranslateCropPatternTS(ID="*",OldCropType="VEGETABLES",NewCropType="VEGETABLES.TR21")
# #
# # WHEAT_FALL AND WHEAT_SPRING - Spring Grain TR21 coefficients used in RGDSS and SPDSS to represent barley, oats, and wheat under the name "Small Grains"
# TranslateCropPatternTS(ID="*",OldCropType="WHEAT_FALL",NewCropType="SMALL_GRAINS.TR21")
# TranslateCropPatternTS(ID="*",OldCropType="WHEAT_SPRING",NewCropType="SMALL_GRAINS.TR21")
# #
# # Step 8 - Write final *.cds file
# # WriteCropPatternTSToStateCU(OutputFile="Results/ArkEx_Simple_HB20180529.cds",WriteHow=OverwriteFile)
# # Uncomment the following to regenerate expected results
# WriteCropPatternTSToStateCU(OutputFile="ExpectedResults/Test_ArkExSimple_out.cds",WriteHow=OverwriteFile)
# WriteCropPatternTSToStateCU(OutputFile="Results/Test_ArkExSimple_out.cds",WriteHow=OverwriteFile)
# #
# # Compare the results
# CompareFiles(InputFile1="ExpectedResults/Test_ArkExSimple_out.cds",InputFile2="Results/Test_ArkExSimple_out.cds",IfDifferent=Warn)
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase_CO_20200720 on RoaringFork
# HydroBase.db_version:  design version: 20200720  last data change: 20200125
# HydroBase table structure for software is at least 2020072020200720
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (6x,i4,5x,6x,i4,a5,a5)
#>
#>  year1            :  Beginning year of data (calendar year).
#>  year2            :  Ending year of data (calendar year).
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>                      >= 0.0 in years with irrigated lands data or filled years.
#>                      -999 in years without irrigated lands data and have not been filled.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0) - INFO ONLY.
#>                      Equal to total/crop acres.
#>                      Fractions should add to 1.0.
#>                      >= 0.0 in years with irrigated lands data or filled years.
#>                      -999 in years without irrigated lands data and have not been filled.
#>  Acres       acres:  Acreage for crop.
#>                      Should sum to the total acres.
#>
#>Yr  CULocation                   TotalArea   NCrop
#>-exb----------exxxxxxxxxxxxxxxxxxb--------eb--------e
#>     CropName                    Fraction    Acres
#>xxxb----------------------------eb--------eb--------e
#>EndHeader
      2000           2016 ACRE CYR  
2000 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2000 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2000 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2000 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2000 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2000 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2000 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2000 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2000 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2000 67AWA015                        -999.000         0
2000 67AWA016                        -999.000         0
2000 67AWA017                        -999.000         0
2000 67AWA018                        -999.000         0
2000 67AWA019                        -999.000         0
2000 67AWA021                        -999.000         0
2000 67AWA022                        -999.000         0
2000 67AWA023                        -999.000         0
2000 67AWA024                        -999.000         0
2000 67AWA602                        -999.000         0
2001 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2001 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2001 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2001 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2001 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2001 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2001 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2001 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2001 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2001 67AWA015                        -999.000         0
2001 67AWA016                        -999.000         0
2001 67AWA017                        -999.000         0
2001 67AWA018                        -999.000         0
2001 67AWA019                        -999.000         0
2001 67AWA021                        -999.000         0
2001 67AWA022                        -999.000         0
2001 67AWA023                        -999.000         0
2001 67AWA024                        -999.000         0
2001 67AWA602                        -999.000         0
2002 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2002 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2002 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2002 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2002 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2002 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2002 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2002 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2002 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2002 67AWA015                        -999.000         0
2002 67AWA016                        -999.000         0
2002 67AWA017                        -999.000         0
2002 67AWA018                        -999.000         0
2002 67AWA019                        -999.000         0
2002 67AWA021                        -999.000         0
2002 67AWA022                        -999.000         0
2002 67AWA023                        -999.000         0
2002 67AWA024                        -999.000         0
2002 67AWA602                        -999.000         0
2003 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2003 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2003 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2003 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2003 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2003 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2003 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2003 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2003 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2003 67AWA015                        -999.000         0
2003 67AWA016                        -999.000         0
2003 67AWA017                        -999.000         0
2003 67AWA018                        -999.000         0
2003 67AWA019                        -999.000         0
2003 67AWA021                        -999.000         0
2003 67AWA022                        -999.000         0
2003 67AWA023                        -999.000         0
2003 67AWA024                        -999.000         0
2003 67AWA602                        -999.000         0
2004 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2004 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2004 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2004 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2004 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2004 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2004 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2004 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2004 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2004 67AWA015                        -999.000         0
2004 67AWA016                        -999.000         0
2004 67AWA017                        -999.000         0
2004 67AWA018                        -999.000         0
2004 67AWA019                        -999.000         0
2004 67AWA021                        -999.000         0
2004 67AWA022                        -999.000         0
2004 67AWA023                        -999.000         0
2004 67AWA024                        -999.000         0
2004 67AWA602                        -999.000         0
2005 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2005 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2005 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2005 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2005 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2005 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2005 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2005 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2005 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2005 67AWA015                        -999.000         0
2005 67AWA016                        -999.000         0
2005 67AWA017                        -999.000         0
2005 67AWA018                        -999.000         0
2005 67AWA019                        -999.000         0
2005 67AWA021                        -999.000         0
2005 67AWA022                        -999.000         0
2005 67AWA023                        -999.000         0
2005 67AWA024                        -999.000         0
2005 67AWA602                        -999.000         0
2006 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2006 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2006 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2006 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2006 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2006 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2006 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2006 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2006 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2006 67AWA015                        -999.000         0
2006 67AWA016                        -999.000         0
2006 67AWA017                        -999.000         0
2006 67AWA018                        -999.000         0
2006 67AWA019                        -999.000         0
2006 67AWA021                        -999.000         0
2006 67AWA022                        -999.000         0
2006 67AWA023                        -999.000         0
2006 67AWA024                        -999.000         0
2006 67AWA602                        -999.000         0
2007 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2007 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2007 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2007 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2007 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2007 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2007 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2007 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2007 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2007 67AWA015                        -999.000         0
2007 67AWA016                        -999.000         0
2007 67AWA017                        -999.000         0
2007 67AWA018                        -999.000         0
2007 67AWA019                        -999.000         0
2007 67AWA021                        -999.000         0
2007 67AWA022                        -999.000         0
2007 67AWA023                        -999.000         0
2007 67AWA024                        -999.000         0
2007 67AWA602                        -999.000         0
2008 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2008 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2008 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2008 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2008 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2008 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2008 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2008 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2008 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2008 67AWA015                        -999.000         0
2008 67AWA016                        -999.000         0
2008 67AWA017                        -999.000         0
2008 67AWA018                        -999.000         0
2008 67AWA019                        -999.000         0
2008 67AWA021                        -999.000         0
2008 67AWA022                        -999.000         0
2008 67AWA023                        -999.000         0
2008 67AWA024                        -999.000         0
2008 67AWA602                        -999.000         0
2009 6600502                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2009 6700556                         -999.000         3
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
2009 6700566                         -999.000         2
     ALFALFA.TR21                    -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
2009 6700587                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2009 6700607D                        -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2009 6700608                         -999.000         7
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2009 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2009 67ADA001                        -999.000         6
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
2009 6700614                         -999.000         9
     ALFALFA.TR21                    -999.000  -999.000
     CORN_GRAIN                      -999.000  -999.000
     CORN_SILAGE                     -999.000  -999.000
     DRY_BEANS.TR21                  -999.000  -999.000
     GRASS_PASTURE.TR21              -999.000  -999.000
     SMALL_GRAINS.TR21               -999.000  -999.000
     SORGHUM_GRAIN.TR21              -999.000  -999.000
     SPRING_GRAIN                    -999.000  -999.000
     VEGETABLES.TR21                 -999.000  -999.000
2009 67AWA015                        -999.000         0
2009 67AWA016                        -999.000         0
2009 67AWA017                        -999.000         0
2009 67AWA018                        -999.000         0
2009 67AWA019                        -999.000         0
2009 67AWA021                        -999.000         0
2009 67AWA022                        -999.000         0
2009 67AWA023                        -999.000         0
2009 67AWA024                        -999.000         0
2009 67AWA602                        -999.000         0
2010 6600502                           15.586         2
     ALFALFA.TR21                       1.000    15.586
     GRASS_PASTURE.TR21                 0.000     0.000
2010 6700556                           27.078         3
     ALFALFA.TR21                       1.000    27.078
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
2010 6700566                            0.000         2
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
2010 6700587                          287.127         7
     ALFALFA.TR21                       0.364   104.646
     CORN_GRAIN                         0.504   144.700
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.006     1.622
     SMALL_GRAINS.TR21                  0.126    36.160
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
2010 6700607D                       29923.598         9
     ALFALFA.TR21                       0.584 17473.891
     CORN_GRAIN                         0.161  4809.254
     CORN_SILAGE                        0.000     0.000
     DRY_BEANS.TR21                     0.001    37.436
     GRASS_PASTURE.TR21                 0.015   460.000
     SMALL_GRAINS.TR21                  0.122  3645.729
     SORGHUM_GRAIN.TR21                 0.117  3487.980
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                     .000     9.307
2010 6700608                         5229.828         7
     ALFALFA.TR21                       0.768  4018.224
     CORN_GRAIN                         0.107   558.692
     GRASS_PASTURE.TR21                 0.008    41.355
     SMALL_GRAINS.TR21                  0.080   418.890
     SORGHUM_GRAIN.TR21                 0.019    97.166
     SPRING_GRAIN                       0.007    34.258
     VEGETABLES.TR21                    0.012    61.244
2010 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2010 67ADA001                        1419.016         6
     ALFALFA.TR21                       0.609   864.554
     CORN_GRAIN                         0.202   286.168
     GRASS_PASTURE.TR21                 0.118   166.921
     SMALL_GRAINS.TR21                  0.027    37.917
     SORGHUM_GRAIN.TR21                 0.031    43.997
     SPRING_GRAIN                       0.014    19.459
2010 6700614                         6552.001         9
     ALFALFA.TR21                       0.506  3312.054
     CORN_GRAIN                         0.153  1003.076
     CORN_SILAGE                        0.006    42.521
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.084   548.501
     SMALL_GRAINS.TR21                  0.194  1268.527
     SORGHUM_GRAIN.TR21                 0.044   285.528
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                    0.014    91.793
2010 67AWA015                           0.000         0
2010 67AWA016                           0.000         0
2010 67AWA017                           0.000         0
2010 67AWA018                           0.000         0
2010 67AWA019                           0.000         0
2010 67AWA021                           0.000         0
2010 67AWA022                           0.000         0
2010 67AWA023                           0.000         0
2010 67AWA024                           0.000         0
2010 67AWA602                           0.000         0
2011 6600502                           10.391         2
     ALFALFA.TR21                       1.000    10.391
     GRASS_PASTURE.TR21                 0.000     0.000
2011 6700556                           28.321         3
     ALFALFA.TR21                       0.637    18.052
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.363    10.269
2011 6700566                            7.495         2
     ALFALFA.TR21                       1.000     7.495
     GRASS_PASTURE.TR21                 0.000     0.000
2011 6700587                          275.436         7
     ALFALFA.TR21                       0.426   117.447
     CORN_GRAIN                         0.350    96.466
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.056    15.427
     SMALL_GRAINS.TR21                  0.167    46.095
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
2011 6700607D                       25788.700         9
     ALFALFA.TR21                       0.642 16550.640
     CORN_GRAIN                         0.126  3241.468
     CORN_SILAGE                        0.000     0.000
     DRY_BEANS.TR21                      .001    24.958
     GRASS_PASTURE.TR21                 0.026   671.028
     SMALL_GRAINS.TR21                  0.110  2831.094
     SORGHUM_GRAIN.TR21                 0.095  2457.987
     SPRING_GRAIN                        .000     5.320
     VEGETABLES.TR21                     .000     6.205
2011 6700608                         5057.869         7
     ALFALFA.TR21                       0.775  3919.772
     CORN_GRAIN                         0.075   378.829
     GRASS_PASTURE.TR21                 0.014    69.320
     SMALL_GRAINS.TR21                  0.096   486.643
     SORGHUM_GRAIN.TR21                 0.028   139.637
     SPRING_GRAIN                       0.005    22.839
     VEGETABLES.TR21                    0.008    40.829
2011 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2011 67ADA001                        1304.393         6
     ALFALFA.TR21                       0.671   874.781
     CORN_GRAIN                         0.146   190.779
     GRASS_PASTURE.TR21                 0.104   135.361
     SMALL_GRAINS.TR21                  0.047    61.169
     SORGHUM_GRAIN.TR21                 0.022    29.331
     SPRING_GRAIN                       0.010    12.973
2011 6700614                         5860.351         9
     ALFALFA.TR21                       0.537  3148.273
     CORN_GRAIN                         0.114   668.717
     CORN_SILAGE                        0.006    36.831
     DRY_BEANS.TR21                     0.003    15.757
     GRASS_PASTURE.TR21                 0.074   436.256
     SMALL_GRAINS.TR21                  0.222  1302.969
     SORGHUM_GRAIN.TR21                 0.032   190.352
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                    0.010    61.195
2011 67AWA015                        -999.000         0
2011 67AWA016                        -999.000         0
2011 67AWA017                        -999.000         0
2011 67AWA018                        -999.000         0
2011 67AWA019                        -999.000         0
2011 67AWA021                        -999.000         0
2011 67AWA022                        -999.000         0
2011 67AWA023                        -999.000         0
2011 67AWA024                        -999.000         0
2011 67AWA602                        -999.000         0
2012 6600502                            5.195         2
     ALFALFA.TR21                       1.000     5.195
     GRASS_PASTURE.TR21                 0.000     0.000
2012 6700556                           29.565         3
     ALFALFA.TR21                       0.305     9.026
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.695    20.539
2012 6700566                           14.990         2
     ALFALFA.TR21                       1.000    14.990
     GRASS_PASTURE.TR21                 0.000     0.000
2012 6700587                          263.744         7
     ALFALFA.TR21                       0.494   130.249
     CORN_GRAIN                         0.183    48.233
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.111    29.232
     SMALL_GRAINS.TR21                  0.212    56.030
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
2012 6700607D                       21653.801         9
     ALFALFA.TR21                       0.722 15627.389
     CORN_GRAIN                         0.077  1673.681
     CORN_SILAGE                        0.000     0.000
     DRY_BEANS.TR21                      .001    12.479
     GRASS_PASTURE.TR21                 0.041   882.056
     SMALL_GRAINS.TR21                  0.093  2016.459
     SORGHUM_GRAIN.TR21                 0.066  1427.994
     SPRING_GRAIN                        .000    10.640
     VEGETABLES.TR21                     .000     3.102
2012 6700608                         4885.910         7
     ALFALFA.TR21                       0.782  3821.321
     CORN_GRAIN                         0.041   198.967
     GRASS_PASTURE.TR21                 0.020    97.286
     SMALL_GRAINS.TR21                  0.113   554.397
     SORGHUM_GRAIN.TR21                 0.037   182.107
     SPRING_GRAIN                       0.002    11.419
     VEGETABLES.TR21                    0.004    20.415
2012 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2012 67ADA001                        1189.770         6
     ALFALFA.TR21                       0.744   885.008
     CORN_GRAIN                         0.080    95.389
     GRASS_PASTURE.TR21                 0.087   103.800
     SMALL_GRAINS.TR21                  0.071    84.421
     SORGHUM_GRAIN.TR21                 0.012    14.666
     SPRING_GRAIN                       0.005     6.486
2012 6700614                         5168.701         9
     ALFALFA.TR21                       0.577  2984.492
     CORN_GRAIN                         0.065   334.359
     CORN_SILAGE                        0.006    31.141
     DRY_BEANS.TR21                     0.006    31.514
     GRASS_PASTURE.TR21                 0.063   324.011
     SMALL_GRAINS.TR21                  0.259  1337.411
     SORGHUM_GRAIN.TR21                 0.018    95.176
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                    0.006    30.598
2012 67AWA015                        -999.000         0
2012 67AWA016                        -999.000         0
2012 67AWA017                        -999.000         0
2012 67AWA018                        -999.000         0
2012 67AWA019                        -999.000         0
2012 67AWA021                        -999.000         0
2012 67AWA022                        -999.000         0
2012 67AWA023                        -999.000         0
2012 67AWA024                        -999.000         0
2012 67AWA602                        -999.000         0
2013 6600502                            0.000         2
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
2013 6700556                           30.808         3
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  1.000    30.808
2013 6700566                           22.485         2
     ALFALFA.TR21                       1.000    22.485
     GRASS_PASTURE.TR21                 0.000     0.000
2013 6700587                          252.053         7
     ALFALFA.TR21                       0.568   143.051
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.171    43.036
     SMALL_GRAINS.TR21                  0.262    65.966
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
2013 6700607D                       17518.903         9
     ALFALFA.TR21                       0.839 14704.138
     CORN_GRAIN                         0.006   105.894
     CORN_SILAGE                        0.000     0.000
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.062  1093.085
     SMALL_GRAINS.TR21                  0.069  1201.824
     SORGHUM_GRAIN.TR21                 0.023   398.002
     SPRING_GRAIN                        .001    15.961
     VEGETABLES.TR21                    0.000     0.000
2013 6700608                         4713.951         7
     ALFALFA.TR21                       0.790  3722.869
     CORN_GRAIN                         0.004    19.104
     GRASS_PASTURE.TR21                 0.027   125.251
     SMALL_GRAINS.TR21                  0.132   622.150
     SORGHUM_GRAIN.TR21                 0.048   224.577
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2013 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2013 67ADA001                        1075.147         6
     ALFALFA.TR21                       0.833   895.235
     CORN_GRAIN                         0.000     0.000
     GRASS_PASTURE.TR21                 0.067    72.240
     SMALL_GRAINS.TR21                  0.100   107.673
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
2013 6700614                         4477.052         9
     ALFALFA.TR21                       0.630  2820.711
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.006    25.451
     DRY_BEANS.TR21                     0.011    47.270
     GRASS_PASTURE.TR21                 0.047   211.766
     SMALL_GRAINS.TR21                  0.306  1371.853
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2013 67AWA015                           0.000         0
2013 67AWA016                           0.000         0
2013 67AWA017                           0.000         0
2013 67AWA018                           0.000         0
2013 67AWA019                           0.000         0
2013 67AWA021                           0.000         0
2013 67AWA022                           0.000         0
2013 67AWA023                           0.000         0
2013 67AWA024                           0.000         0
2013 67AWA602                           0.000         0
2014 6600502                            0.000         2
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
2014 6700556                            0.000         3
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
2014 6700566                           22.485         2
     ALFALFA.TR21                       1.000    22.485
     GRASS_PASTURE.TR21                 0.000     0.000
2014 6700587                          262.845         7
     ALFALFA.TR21                       0.651   171.234
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.101    26.665
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.133    35.074
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.114    29.871
2014 6700607D                       21768.235         9
     ALFALFA.TR21                       0.663 14428.114
     CORN_GRAIN                         0.040   861.226
     CORN_SILAGE                        0.012   270.428
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.030   662.819
     SMALL_GRAINS.TR21                  0.095  2066.745
     SORGHUM_GRAIN.TR21                 0.156  3386.948
     SPRING_GRAIN                       0.004    91.954
     VEGETABLES.TR21                    0.000     0.000
2014 6700608                         4856.204         7
     ALFALFA.TR21                       0.821  3987.679
     CORN_GRAIN                         0.080   389.658
     GRASS_PASTURE.TR21                 0.027   132.318
     SMALL_GRAINS.TR21                  0.016    76.891
     SORGHUM_GRAIN.TR21                 0.039   189.630
     SPRING_GRAIN                       0.007    33.280
     VEGETABLES.TR21                    0.010    46.748
2014 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2014 67ADA001                        1233.832         6
     ALFALFA.TR21                       0.699   862.113
     CORN_GRAIN                         0.000     0.000
     GRASS_PASTURE.TR21                 0.004     4.884
     SMALL_GRAINS.TR21                  0.183   225.723
     SORGHUM_GRAIN.TR21                 0.114   141.112
     SPRING_GRAIN                       0.000     0.000
2014 6700614                         6113.395         9
     ALFALFA.TR21                       0.462  2823.118
     CORN_GRAIN                         0.011    69.116
     CORN_SILAGE                        0.000     0.000
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.041   253.341
     SMALL_GRAINS.TR21                  0.457  2794.004
     SORGHUM_GRAIN.TR21                 0.023   140.372
     SPRING_GRAIN                       0.005    33.445
     VEGETABLES.TR21                    0.000     0.000
2014 67AWA015                           0.000         0
2014 67AWA016                           0.000         0
2014 67AWA017                           0.000         0
2014 67AWA018                           0.000         0
2014 67AWA019                           0.000         0
2014 67AWA021                           0.000         0
2014 67AWA022                           0.000         0
2014 67AWA023                           0.000         0
2014 67AWA024                           0.000         0
2014 67AWA602                           0.000         0
2015 6600502                           24.591         2
     ALFALFA.TR21                       0.537    13.199
     GRASS_PASTURE.TR21                 0.463    11.392
2015 6700556                            0.000         3
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
2015 6700566                            0.000         2
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
2015 6700587                          285.505         7
     ALFALFA.TR21                       0.600   171.234
     CORN_GRAIN                         0.093    26.665
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.169    48.240
     SMALL_GRAINS.TR21                  0.138    39.366
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
2015 6700607D                       29495.693         9
     ALFALFA.TR21                       0.532 15692.433
     CORN_GRAIN                         0.100  2961.693
     CORN_SILAGE                        0.004   131.620
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.052  1525.187
     SMALL_GRAINS.TR21                  0.111  3269.214
     SORGHUM_GRAIN.TR21                 0.198  5839.868
     SPRING_GRAIN                       0.003    75.676
     VEGETABLES.TR21                    0.000     0.000
2015 6700608                         5360.455         7
     ALFALFA.TR21                       0.824  4417.565
     CORN_GRAIN                         0.049   264.479
     GRASS_PASTURE.TR21                 0.043   227.993
     SMALL_GRAINS.TR21                  0.036   192.589
     SORGHUM_GRAIN.TR21                 0.035   185.191
     SPRING_GRAIN                       0.014    72.638
     VEGETABLES.TR21                    0.000     0.000
2015 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2015 67ADA001                        1138.751         6
     ALFALFA.TR21                       0.705   802.968
     CORN_GRAIN                         0.000     0.000
     GRASS_PASTURE.TR21                 0.039    44.764
     SMALL_GRAINS.TR21                  0.040    44.984
     SORGHUM_GRAIN.TR21                 0.216   246.034
     SPRING_GRAIN                       0.000     0.000
2015 6700614                         5729.634         9
     ALFALFA.TR21                       0.624  3577.956
     CORN_GRAIN                         0.040   230.007
     CORN_SILAGE                        0.092   524.520
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.046   265.717
     SMALL_GRAINS.TR21                  0.021   121.898
     SORGHUM_GRAIN.TR21                 0.165   944.604
     SPRING_GRAIN                       0.011    64.932
     VEGETABLES.TR21                    0.000     0.000
2015 67AWA015                           0.000         0
2015 67AWA016                           0.000         0
2015 67AWA017                           0.000         0
2015 67AWA018                           0.000         0
2015 67AWA019                           0.000         0
2015 67AWA021                           0.000         0
2015 67AWA022                           0.000         0
2015 67AWA023                           0.000         0
2015 67AWA024                           0.000         0
2015 67AWA602                           0.000         0
2016 6600502                            0.000         2
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
2016 6700556                           57.886         3
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 1.000    57.886
     SMALL_GRAINS.TR21                  0.000     0.000
2016 6700566                           22.485         2
     ALFALFA.TR21                       0.000     0.000
     GRASS_PASTURE.TR21                 1.000    22.485
2016 6700587                          285.505         7
     ALFALFA.TR21                       0.468   133.578
     CORN_GRAIN                         0.272    77.546
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.046    13.166
     SMALL_GRAINS.TR21                  0.123    35.074
     SORGHUM_GRAIN.TR21                 0.092    26.142
     SPRING_GRAIN                       0.000     0.000
2016 6700607D                       31884.546         9
     ALFALFA.TR21                       0.485 15465.820
     CORN_GRAIN                         0.179  5716.868
     CORN_SILAGE                        0.016   502.714
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.096  3067.501
     SMALL_GRAINS.TR21                  0.123  3921.734
     SORGHUM_GRAIN.TR21                 0.101  3209.909
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2016 6700608                         5580.696         7
     ALFALFA.TR21                       0.730  4074.045
     CORN_GRAIN                         0.076   424.211
     GRASS_PASTURE.TR21                 0.044   243.718
     SMALL_GRAINS.TR21                  0.126   702.457
     SORGHUM_GRAIN.TR21                 0.024   136.265
     SPRING_GRAIN                       0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2016 6700610                            0.000         9
     ALFALFA.TR21                       0.000     0.000
     CORN_GRAIN                         0.000     0.000
     CORN_SILAGE                        0.000     0.000
     GRASS_PASTURE.TR21                 0.000     0.000
     SMALL_GRAINS.TR21                  0.000     0.000
     SORGHUM_GRAIN.TR21                 0.000     0.000
     SPRING_GRAIN                       0.000     0.000
     SUGAR_BEETS.TR21                   0.000     0.000
     VEGETABLES.TR21                    0.000     0.000
2016 67ADA001                        1010.113         6
     ALFALFA.TR21                       0.769   776.912
     CORN_GRAIN                         0.020    19.899
     GRASS_PASTURE.TR21                 0.045    45.686
     SMALL_GRAINS.TR21                  0.047    47.504
     SORGHUM_GRAIN.TR21                 0.119   120.111
     SPRING_GRAIN                       0.000     0.000
2016 6700614                         6035.873         9
     ALFALFA.TR21                       0.573  3458.173
     CORN_GRAIN                         0.162   977.328
     CORN_SILAGE                        0.000     0.000
     DRY_BEANS.TR21                     0.000     0.000
     GRASS_PASTURE.TR21                 0.123   744.169
     SMALL_GRAINS.TR21                  0.053   320.763
     SORGHUM_GRAIN.TR21                 0.056   335.978
     SPRING_GRAIN                       0.033   199.462
     VEGETABLES.TR21                    0.000     0.000
2016 67AWA015                           0.000         0
2016 67AWA016                           0.000         0
2016 67AWA017                           0.000         0
2016 67AWA018                           0.000         0
2016 67AWA019                           0.000         0
2016 67AWA021                           0.000         0
2016 67AWA022                           0.000         0
2016 67AWA023                           0.000         0
2016 67AWA024                           0.000         0
2016 67AWA602                           0.000         0
