#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 5.00.06.dev (2021-01-05)
# user:         sam
# date:         Mon Jan 18 01:56:15 America/Denver 2021
# host:         RoaringFork
# directory:    C:\Users\sam\cdss-dev\StateDMI\git-repos\cdss-app-statedmi-test\test\regression\commands\WriteResponseToStateMod\Data
# command line: StateDMI
#  -home test\operational\CDSS
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Users\sam\cdss-dev\StateDMI\git-repos\cdss-app-statedmi-test\test\regression\commands\ReadCropPatternTSFromHydroBase\Test_ReadCropPatternTSFromHydroBase_ArkExGwOnly.statedmi"
# Commands: 
# # Test reading crop pattern time series data from HydroBase:
# # - this is a small number of groundwater-only structures with aggregation using WDID parts
# StartLog(LogFile="Results/Test_ReadCropPatternTSFromHydroBase_ArkExGwOnly.StateDMI.log")
# RemoveFile(InputFile="Results\Test_ReadCropPatternTSFromHydroBase_ArkExGwOnly_out.ipy",IfNotFound=Ignore)
# SetOutputPeriod(OutputStart="2000",OutputEnd="2016")
# SetCULocation(ID="67AWA015",IfNotFound=Add)
# SetCULocation(ID="67AWA016",IfNotFound=Add)
# SetCULocation(ID="67AWA017",IfNotFound=Add)
# SetCULocation(ID="67AWA018",IfNotFound=Add)
# SetCULocation(ID="67AWA019",IfNotFound=Add)
# SetCULocation(ID="67AWA021",IfNotFound=Add)
# SetCULocation(ID="67AWA022",IfNotFound=Add)
# SetCULocation(ID="67AWA023",IfNotFound=Add)
# SetCULocation(ID="67AWA024",IfNotFound=Add)
# SetCULocation(ID="67AWA602",IfNotFound=Add)
# # Set aggregates using list file and column numbers (traditional approach)
# SetWellAggregateFromList(ListFile="Data\ArkEx_GWAgg_Only.csv",TableID="WellAggregateTable",PartType=Well,IDCol="1",PartIDsCol="2",PartIDTypeColumn="3",PartsListedHow=InColumn)
# # Set aggregates using list file and column names (new approach)
# # SetWellAggregateFromList(ListFile="Data\ArkEx_GWAgg_Only.csv",TableID="WellAggregateTable",PartType=Well,IDCol="Structure_ID",PartIDsCol="GW_ID1",PartIDTypeColumn="GW_TYPE1",PartsListedHow=InColumn)
# CreateCropPatternTSForCULocations(ID="*",Units="ACRE")
# ReadCropPatternTSFromHydroBase(ID="*")
# # Uncomment the following command to regenerate the expected results.
# WriteCropPatternTSToStateCU(OutputFile="ExpectedResults/Test_ReadCropPatternTSFromHydroBase_ArkExGwOnly_out.cds")
# WriteCropPatternTSToStateCU(OutputFile="Results/Test_ReadCropPatternTSFromHydroBase_ArkExGwOnly_out.cds")
# CompareFiles(InputFile1="ExpectedResults/Test_ReadCropPatternTSFromHydroBase_ArkExGwOnly_out.cds",InputFile2="Results/Test_ReadCropPatternTSFromHydroBase_ArkExGwOnly_out.cds",IfDifferent=Warn)
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase_CO_20200720 on RoaringFork
# HydroBase.db_version:  design version: 20200720  last data change: 20200125
# HydroBase table structure for software is at least 2020072020200720
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#>  StateCU Crop Patterns (CDS) File
#>
#>  Header format (6x,i4,5x,6x,i4,a5,a5)
#>
#>  year1            :  Beginning year of data (calendar year).
#>  year2            :  Ending year of data (calendar year).
#>  yeartype         :  Year type (always CYR for calendar).
#>
#>  Record 1 format (i4,1x,a12,18x,f10.0,i10) - for each year/CULocation.
#>
#>  Yr            tyr:  Year for data (calendar year).
#>  CULocation    tid:  CU Location ID (e.g., structure/station).
#>  TotalAcres ttacre:  Total acreage for the CU Location.
#>                      >= 0.0 in years with irrigated lands data or filled years.
#>                      -999 in years without irrigated lands data and have not been filled.
#>  NCrop            :  Number of crops at location/year.
#>
#>  Record 2 format (5x,a30,f10.3,f10.3) - for each crop for Record 1
#>
#>  CropName    cropn:  Crop name (e.g., ALFALFA).
#>  Fraction     tpct:  Decimal fraction of total acreage
#>                      for the crop (0.0 to 1.0) - INFO ONLY.
#>                      Equal to total/crop acres.
#>                      Fractions should add to 1.0.
#>                      >= 0.0 in years with irrigated lands data or filled years.
#>                      -999 in years without irrigated lands data and have not been filled.
#>  Acres       acres:  Acreage for crop.
#>                      Should sum to the total acres.
#>
#>Yr  CULocation                   TotalArea   NCrop
#>-exb----------exxxxxxxxxxxxxxxxxxb--------eb--------e
#>     CropName                    Fraction    Acres
#>xxxb----------------------------eb--------eb--------e
#>EndHeader
      2000           2016 ACRE CYR  
2000 67AWA015                        -999.000         0
2000 67AWA016                        -999.000         0
2000 67AWA017                        -999.000         0
2000 67AWA018                        -999.000         0
2000 67AWA019                        -999.000         0
2000 67AWA021                        -999.000         0
2000 67AWA022                        -999.000         0
2000 67AWA023                        -999.000         0
2000 67AWA024                        -999.000         0
2000 67AWA602                        -999.000         0
2001 67AWA015                        -999.000         0
2001 67AWA016                        -999.000         0
2001 67AWA017                        -999.000         0
2001 67AWA018                        -999.000         0
2001 67AWA019                        -999.000         0
2001 67AWA021                        -999.000         0
2001 67AWA022                        -999.000         0
2001 67AWA023                        -999.000         0
2001 67AWA024                        -999.000         0
2001 67AWA602                        -999.000         0
2002 67AWA015                        -999.000         0
2002 67AWA016                        -999.000         0
2002 67AWA017                        -999.000         0
2002 67AWA018                        -999.000         0
2002 67AWA019                        -999.000         0
2002 67AWA021                        -999.000         0
2002 67AWA022                        -999.000         0
2002 67AWA023                        -999.000         0
2002 67AWA024                        -999.000         0
2002 67AWA602                        -999.000         0
2003 67AWA015                        -999.000         0
2003 67AWA016                        -999.000         0
2003 67AWA017                        -999.000         0
2003 67AWA018                        -999.000         0
2003 67AWA019                        -999.000         0
2003 67AWA021                        -999.000         0
2003 67AWA022                        -999.000         0
2003 67AWA023                        -999.000         0
2003 67AWA024                        -999.000         0
2003 67AWA602                        -999.000         0
2004 67AWA015                        -999.000         0
2004 67AWA016                        -999.000         0
2004 67AWA017                        -999.000         0
2004 67AWA018                        -999.000         0
2004 67AWA019                        -999.000         0
2004 67AWA021                        -999.000         0
2004 67AWA022                        -999.000         0
2004 67AWA023                        -999.000         0
2004 67AWA024                        -999.000         0
2004 67AWA602                        -999.000         0
2005 67AWA015                        -999.000         0
2005 67AWA016                        -999.000         0
2005 67AWA017                        -999.000         0
2005 67AWA018                        -999.000         0
2005 67AWA019                        -999.000         0
2005 67AWA021                        -999.000         0
2005 67AWA022                        -999.000         0
2005 67AWA023                        -999.000         0
2005 67AWA024                        -999.000         0
2005 67AWA602                        -999.000         0
2006 67AWA015                        -999.000         0
2006 67AWA016                        -999.000         0
2006 67AWA017                        -999.000         0
2006 67AWA018                        -999.000         0
2006 67AWA019                        -999.000         0
2006 67AWA021                        -999.000         0
2006 67AWA022                        -999.000         0
2006 67AWA023                        -999.000         0
2006 67AWA024                        -999.000         0
2006 67AWA602                        -999.000         0
2007 67AWA015                        -999.000         0
2007 67AWA016                        -999.000         0
2007 67AWA017                        -999.000         0
2007 67AWA018                        -999.000         0
2007 67AWA019                        -999.000         0
2007 67AWA021                        -999.000         0
2007 67AWA022                        -999.000         0
2007 67AWA023                        -999.000         0
2007 67AWA024                        -999.000         0
2007 67AWA602                        -999.000         0
2008 67AWA015                        -999.000         0
2008 67AWA016                        -999.000         0
2008 67AWA017                        -999.000         0
2008 67AWA018                        -999.000         0
2008 67AWA019                        -999.000         0
2008 67AWA021                        -999.000         0
2008 67AWA022                        -999.000         0
2008 67AWA023                        -999.000         0
2008 67AWA024                        -999.000         0
2008 67AWA602                        -999.000         0
2009 67AWA015                        -999.000         0
2009 67AWA016                        -999.000         0
2009 67AWA017                        -999.000         0
2009 67AWA018                        -999.000         0
2009 67AWA019                        -999.000         0
2009 67AWA021                        -999.000         0
2009 67AWA022                        -999.000         0
2009 67AWA023                        -999.000         0
2009 67AWA024                        -999.000         0
2009 67AWA602                        -999.000         0
2010 67AWA015                        -999.000         0
2010 67AWA016                        -999.000         0
2010 67AWA017                        -999.000         0
2010 67AWA018                        -999.000         0
2010 67AWA019                        -999.000         0
2010 67AWA021                        -999.000         0
2010 67AWA022                        -999.000         0
2010 67AWA023                        -999.000         0
2010 67AWA024                        -999.000         0
2010 67AWA602                        -999.000         0
2011 67AWA015                        -999.000         0
2011 67AWA016                        -999.000         0
2011 67AWA017                        -999.000         0
2011 67AWA018                        -999.000         0
2011 67AWA019                        -999.000         0
2011 67AWA021                        -999.000         0
2011 67AWA022                        -999.000         0
2011 67AWA023                        -999.000         0
2011 67AWA024                        -999.000         0
2011 67AWA602                        -999.000         0
2012 67AWA015                        -999.000         0
2012 67AWA016                        -999.000         0
2012 67AWA017                        -999.000         0
2012 67AWA018                        -999.000         0
2012 67AWA019                        -999.000         0
2012 67AWA021                        -999.000         0
2012 67AWA022                        -999.000         0
2012 67AWA023                        -999.000         0
2012 67AWA024                        -999.000         0
2012 67AWA602                        -999.000         0
2013 67AWA015                        -999.000         0
2013 67AWA016                        -999.000         0
2013 67AWA017                        -999.000         0
2013 67AWA018                        -999.000         0
2013 67AWA019                        -999.000         0
2013 67AWA021                        -999.000         0
2013 67AWA022                        -999.000         0
2013 67AWA023                        -999.000         0
2013 67AWA024                        -999.000         0
2013 67AWA602                        -999.000         0
2014 67AWA015                        -999.000         0
2014 67AWA016                        -999.000         0
2014 67AWA017                        -999.000         0
2014 67AWA018                        -999.000         0
2014 67AWA019                        -999.000         0
2014 67AWA021                        -999.000         0
2014 67AWA022                        -999.000         0
2014 67AWA023                        -999.000         0
2014 67AWA024                        -999.000         0
2014 67AWA602                        -999.000         0
2015 67AWA015                        -999.000         0
2015 67AWA016                        -999.000         0
2015 67AWA017                        -999.000         0
2015 67AWA018                        -999.000         0
2015 67AWA019                        -999.000         0
2015 67AWA021                        -999.000         0
2015 67AWA022                        -999.000         0
2015 67AWA023                        -999.000         0
2015 67AWA024                        -999.000         0
2015 67AWA602                        -999.000         0
2016 67AWA015                        -999.000         0
2016 67AWA016                        -999.000         0
2016 67AWA017                        -999.000         0
2016 67AWA018                        -999.000         0
2016 67AWA019                        -999.000         0
2016 67AWA021                        -999.000         0
2016 67AWA022                        -999.000         0
2016 67AWA023                        -999.000         0
2016 67AWA024                        -999.000         0
2016 67AWA602                        -999.000         0
